#!/usr/bin/env bash
PROFILE=${MITO_PROFILE:-generic}
CONDA_ROOT=${CONDA_ROOT:-}
MITOS2_PY=${MITOS2_PY:-}
MITOS2_REFDIR=${MITOS2_REFDIR:-}
MITOS2_EXTRA_PATH=${MITOS2_EXTRA_PATH:-}
MITOS2_RSCRIPT=${MITOS2_RSCRIPT:-}
PLOT_PY=${PLOT_PY:-}
MINIMAP2=${MINIMAP2:-}
GETORGANELLE=${GETORGANELLE:-}
MITOFLEX=${MITOFLEX:-}
MITOFLEX_ROOT=${MITOFLEX_ROOT:-}
MITOFLEX_PYTHON=${MITOFLEX_PYTHON:-}
NOVOPLASTY=${NOVOPLASTY:-}
MITOZ=${MITOZ:-}
MITOFINDER=${MITOFINDER:-}
MITOS2_REFSEQVER=${MITOS2_REFSEQVER:-refseq89m}
export PROFILE CONDA_ROOT MITOS2_PY MITOS2_REFDIR MITOS2_REFSEQVER MITOS2_EXTRA_PATH MITOS2_RSCRIPT PLOT_PY MINIMAP2 \
  GETORGANELLE MITOFLEX MITOFLEX_ROOT MITOFLEX_PYTHON NOVOPLASTY MITOZ MITOFINDER
