#!/usr/bin/env bash
PROFILE=${MITO_PROFILE:-generic}
CONDA_ROOT=${CONDA_ROOT:-}
MITOS2_PY=${MITOS2_PY:-}
MITOS2_REFDIR=${MITOS2_REFDIR:-}
MITOS2_EXTRA_PATH=${MITOS2_EXTRA_PATH:-}
PLOT_PY=${PLOT_PY:-}
MINIMAP2=${MINIMAP2:-}
MITOS2_REFSEQVER=${MITOS2_REFSEQVER:-refseq89m}
export PROFILE CONDA_ROOT MITOS2_PY MITOS2_REFDIR MITOS2_REFSEQVER MITOS2_EXTRA_PATH PLOT_PY MINIMAP2
